### ISSUE TITLE
Adding a new item creates an unnecessary blank entry

### ISSUE THREAD

**Issue by oelias27** [sidneyyin/todo#1]
## Expected Behavior

When a new item is added, only that item should be appended to the list.

## Current Behavior

The new item is added to the list, but a blank item is also added to the list.

## Steps to Reproduce

1. Fill in text in 'Enter new item' input 
1. Click 'Add Item' button
1. Observe list behavior

**Comment by sidneyyin** [comment]
Thanks!  I actually programmed that into place to encourage users to realize they can add items.  But I can certainly take out blank spaces!

**Comment by oelias27** [comment]
Having that blank line in place makes sense, but is there supposed to be more than one after adding an item? See below

![todo](https://user-images.githubusercontent.com/19161338/59810356-b54f7800-92b9-11e9-967e-a4b2a32d3c01.gif)

**Comment by sidneyyin** [comment]
Ah thanks!  I'll take a look!
